# Generated by Django 4.0.5 on 2022-07-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(choices=[('m', 'Мужчина'), ('f', 'Женщина')], default='', max_length=1, verbose_name='Телефон'),
        ),
    ]
