# Generated by Django 4.0.5 on 2022-08-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'permissions': (('posts', 'users'),)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('posts', 'users'),)},
        ),
    ]
